### ISSUE TITLE
[Bug:(Crawler)] Missing sqlite schema

### ISSUE THREAD

**Issue by pdomagala** [MohamedBassem/hoarder-app#103]
Upon setting up the project, I encountered an error in the logs indicating the absence of the bookmarkLinks table in the SQLite database. This issue is hindering the proper functioning of the crawler component within the project.

**App details:**
App version: v0.12.1 (release) (latest release docker image from ghcr.io)
NodeJS: v21.7.3

**Steps to Reproduce:**
1. Set up the project for indexing bookmarks.
2. Observe the logs from the container (worker).

**Logs:**
```
> @hoarder/workers@0.1.0 start:prod /app/apps/workers
> tsx index.ts

2024-04-16T15:20:06.475Z info: Workers version: 0.12.1
2024-04-16T15:20:06.481Z info: [Crawler] Connecting to existing browser instance: http://chrome:9222
(node:34) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
2024-04-16T15:20:06.491Z info: [Crawler] Successfully resolved IP address, new address: http://172.20.0.2:9222/
2024-04-16T15:20:06.684Z info: Starting crawler worker ...
2024-04-16T15:20:06.685Z info: Starting inference worker ...
2024-04-16T15:20:06.686Z info: Starting search indexing worker ...
2024-04-16T15:20:07.611Z error: [Crawler][5] Crawling job failed: SqliteError: no such table: bookmarkLinks

/app/apps/workers/node_modules/.pnpm/better-sqlite3@9.4.3/node_modules/better-sqlite3/lib/methods/wrappers.js:5
	return this[cppdb].prepare(sql, this, false);
	                   ^
SqliteError: no such table: bookmarkLinks
    at Database.prepare (/app/apps/workers/node_modules/.pnpm/better-sqlite3@9.4.3/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at BetterSQLiteSession.prepareQuery (/app/apps/workers/node_modules/.pnpm/drizzle-orm@0.29.4_better-sqlite3@9.4.3/node_modules/drizzle-orm/better-sqlite3/session.cjs:42:30)
    at BetterSQLiteSession.prepareOneTimeQuery (/app/apps/workers/node_modules/.pnpm/drizzle-orm@0.29.4_better-sqlite3@9.4.3/node_modules/drizzle-orm/sqlite-core/session.cjs:91:17)
    at QueryPromise._prepare (/app/apps/workers/node_modules/.pnpm/drizzle-orm@0.29.4_better-sqlite3@9.4.3/node_modules/drizzle-orm/sqlite-core/query-builders/update.cjs:101:81)
    at QueryPromise.run (/app/apps/workers/node_modules/.pnpm/drizzle-orm@0.29.4_better-sqlite3@9.4.3/node_modules/drizzle-orm/sqlite-core/query-builders/update.cjs:111:17)
    at QueryPromise.execute (/app/apps/workers/node_modules/.pnpm/drizzle-orm@0.29.4_better-sqlite3@9.4.3/node_modules/drizzle-orm/sqlite-core/query-builders/update.cjs:123:54)
    at QueryPromise.then (/app/apps/workers/node_modules/.pnpm/drizzle-orm@0.29.4_better-sqlite3@9.4.3/node_modules/drizzle-orm/query-promise.cjs:44:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'SQLITE_ERROR'
}

Node.js v21.7.3
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by MohamedBassem** [comment]
Hi, that usually means that the DATA_DIR (or the volume mount) of the workers is incorrectly set up. Both the workers and the web containers should point to the same directory.

**Comment by Batman313v** [comment]
Can confirm this that this solved it for me. I had changed the default volumes and didn't pay close enough attention to that

**Comment by MohamedBassem** [comment]
Glad it solved the problem for you!
