### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by lucius346346** [MohamedBassem/hoarder-app#118]
Search doesn't seem to work for me in either web or mobile version.

**App details:**
App version: 0.12.2 (release) (latest release docker image from ghcr.io)

**Steps to Reproduce:**
1. Type any character in searchbox
2. "No bookmarks" shows up

**Logs:**
[_hoarder-meilisearch-1_logs.txt](https://github.com/MohamedBassem/hoarder-app/files/15059488/_hoarder-meilisearch-1_logs.txt)

**Comment by MohamedBassem** [comment]
Hey, this could indicate multiple things:

1. The worker container is failing to index in meilisearch. You should find errors in the worker container if that's the case.
2. You lost your meilisearch index (are you sure you have it on a persistent storage?)

If you broke your search index, you can trigger a reindex from the admin panel, it should be extremely fast. However, let's try to figure out what happened as well to prevent it from happening again.

**Comment by lucius346346** [comment]
1. It doesn't seem to be any error, only: 2024-04-22T08:09:15.063Z info: [search][542] Completed successfully
2. Index seems to exist:
![image](https://github.com/MohamedBassem/hoarder-app/assets/43910504/1e7306cc-b4ee-492d-8058-3757205aa490)

Unfortunately, reindexing did nothing.

**Comment by MohamedBassem** [comment]
Maybe the web container is failing to talk to meilisearch? Do you have anything special in your .en setup? Is the meilisearch master key and address correctly propagated to the web container?

**Comment by MohamedBassem** [comment]
would you be interested in hopping onto discord for a more interactive debugging session? 😅

**Comment by iweputo** [comment]
I have the same issue now, cant Reindex through admin panel => "Fetch Failed", i havent changed directories of meilisearch and it has suddenly stopped working. What can it be?

**Comment by chicheese** [comment]
Same. I checked Docker logs for meilisearch and am getting a 
`INFO HTTP request{method=GET host="meilisearch:7700" route=/indexes query_parameters= user_agent=node status_code=401 error=The Authorization header is missing. It must use the bearer authorization method.}`

When I reindex through admin panel I get an error that also says "The Authorization header is missing. It must use the bearer authorization method."

Edit:
Never mind, I incorrectly configured my docker compose environment, forgot to add the `MEILI_MASTER_KEY:` variable. After adding that, redeploying the stack, and going to the Karakeep web admin panel and reindexing all bookmarks, works like a charm.

**Comment by deepblue597** [comment]
Same issue here. Searching is not working and the logs of karakeep-web-app say 
```
2025-10-29T16:54:21.966Z error: [search][8804] search job failed: MeiliSearchRequestError: Request to http://meilisearch:7700/indexes has failed
MeiliSearchRequestError: Request to http://meilisearch:7700/indexes has failed
    at file:///app/apps/workers/dist/plugins-search-meilisearch-CaCsu9Fv.js:279:10
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async HttpRequests.request (file:///app/apps/workers/dist/plugins-search-meilisearch-CaCsu9Fv.js:278:20)
    at async HttpRequests.get (file:///app/apps/workers/dist/plugins-search-meilisearch-CaCsu9Fv.js:307:10)
    at async MeiliSearch.getRawIndexes (file:///app/apps/workers/dist/plugins-search-meilisearch-CaCsu9Fv.js:1535:10)
    at async MeiliSearch.getIndexes (file:///app/apps/workers/dist/plugins-search-meilisearch-CaCsu9Fv.js:1520:22)
    at async MeiliSearchProvider.getClient (file:///app/apps/workers/dist/plugins-search-meilisearch-CaCsu9Fv.js:1972:19)
    at async PluginManager.getClient (file:///app/apps/workers/dist/plugins-Gk0CKWDA.js:12280:10)
    at async Object.runSearchIndexing [as run] (file:///app/apps/workers/dist/index.js:88661:23)
    at async Runner.runOnce (file:///app/apps/workers/node_modules/.pnpm/liteque@0.6.0_@opentelemetry+api@1.9.0_@types+better-sqlite3@7.6.13_@types+react@19.1.11_bett_q46iwo2f32qriczoxxudwy6mbu/node_modules/liteque/dist/index.js:229:4)
Error [TRPCError]: Request to http://meilisearch:7700/indexes has failed
    at <unknown> (.next/server/chunks/1413.js:3:834)
    at async w.request (.next/server/chunks/1413.js:3:810)
    at async w.get (.next/server/chunks/1413.js:3:1286)
    at async b.getRawIndexes (.next/server/chunks/1413.js:3:15652)
    at async b.getIndexes (.next/server/chunks/1413.js:3:15510)
    at async D.getClient (.next/server/chunks/1413.js:4:3134)
    at async o.getClient (.next/server/chunks/3504.js:1:3546)
    at async (.next/server/chunks/3014.js:1:20282)
    at async n.middlewares (.next/server/chunks/3487.js:28:6854) {
  code: 'INTERNAL_SERVER_ERROR',
  [cause]: Error [MeiliSearchRequestError]: Request to http://meilisearch:7700/indexes has failed
      at <unknown> (.next/server/chunks/1413.js:3:834)
      at async w.request (.next/server/chunks/1413.js:3:810)
      at async w.get (.next/server/chunks/1413.js:3:1286)
      at async b.getRawIndexes (.next/server/chunks/1413.js:3:15652)
      at async b.getIndexes (.next/server/chunks/1413.js:3:15510)
      at async D.getClient (.next/server/chunks/1413.js:4:3134)
      at async o.getClient (.next/server/chunks/3504.js:1:3546)
      at async (.next/server/chunks/3014.js:1:20282)
      at async n.middlewares (.next/server/chunks/3487.js:28:6854) {
    [cause]: TypeError: fetch failed
        at async w.request (.next/server/chunks/1413.js:3:810)
        at async w.get (.next/server/chunks/1413.js:3:1286)
        at async b.getRawIndexes (.next/server/chunks/1413.js:3:15652)
        at async b.getIndexes (.next/server/chunks/1413.js:3:15510)
        at async D.getClient (.next/server/chunks/1413.js:4:3134)
        at async o.getClient (.next/server/chunks/3504.js:1:3546)
        at async (.next/server/chunks/3014.js:1:20282)
        at async n.middlewares (.next/server/chunks/3487.js:28:6854) {
      [cause]: [Error [ConnectTimeoutError]: Connect Timeout Error (attempted address: meilisearch:7700, timeout: 10000ms)] {
        code: 'UND_ERR_CONNECT_TIMEOUT'
      }
    }
  }
}
```
