### ISSUE TITLE
Crawling failing due to missing SQLite bookmarks table

### ISSUE THREAD

**Issue by talentedmrripley** [MohamedBassem/hoarder-app#138]
Fresh install of Hoarder, I can access the website and add bookmarks but watching the logs of the worker container I see repeating errors, shown below, indicating a missing SQLite table.  So far I've only added a single bookmark for testing purposes.  No other containers are throwing errors.

`
> @hoarder/workers@0.1.0 start:prod /app/apps/workers
> tsx index.ts
2024-05-04T19:40:18.540Z info: Workers version: 0.13.1
2024-05-04T19:40:18.552Z info: [Crawler] Connecting to existing browser instance: http://hoarder-chrome:9222
(node:34) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
2024-05-04T19:40:18.572Z info: [Crawler] Successfully resolved IP address, new address: http://192.168.224.4:9222/
2024-05-04T19:40:18.886Z info: Starting crawler worker ...
2024-05-04T19:40:18.889Z info: Starting inference worker ...
2024-05-04T19:40:18.890Z info: Starting search indexing worker ...
2024-05-04T19:40:21.315Z error: [Crawler][2] Crawling job failed: SqliteError: no such table: bookmarks
/app/apps/workers/node_modules/.pnpm/better-sqlite3@9.4.3/node_modules/better-sqlite3/lib/methods/wrappers.js:5
	return this[cppdb].prepare(sql, this, false);
	                   ^
SqliteError: no such table: bookmarkLinks
    at Database.prepare (/app/apps/workers/node_modules/.pnpm/better-sqlite3@9.4.3/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at BetterSQLiteSession.prepareQuery (/app/apps/workers/node_modules/.pnpm/drizzle-orm@0.29.4_better-sqlite3@9.4.3/node_modules/drizzle-orm/better-sqlite3/session.cjs:42:30)
    at BetterSQLiteSession.prepareOneTimeQuery (/app/apps/workers/node_modules/.pnpm/drizzle-orm@0.29.4_better-sqlite3@9.4.3/node_modules/drizzle-orm/sqlite-core/session.cjs:91:17)
    at QueryPromise._prepare (/app/apps/workers/node_modules/.pnpm/drizzle-orm@0.29.4_better-sqlite3@9.4.3/node_modules/drizzle-orm/sqlite-core/query-builders/update.cjs:101:81)
    at QueryPromise.run (/app/apps/workers/node_modules/.pnpm/drizzle-orm@0.29.4_better-sqlite3@9.4.3/node_modules/drizzle-orm/sqlite-core/query-builders/update.cjs:111:17)
    at QueryPromise.execute (/app/apps/workers/node_modules/.pnpm/drizzle-orm@0.29.4_better-sqlite3@9.4.3/node_modules/drizzle-orm/sqlite-core/query-builders/update.cjs:123:54)
    at QueryPromise.then (/app/apps/workers/node_modules/.pnpm/drizzle-orm@0.29.4_better-sqlite3@9.4.3/node_modules/drizzle-orm/query-promise.cjs:44:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'SQLITE_ERROR'
}
Node.js v21.7.3
 ELIFECYCLE  Command failed with exit code 1.
`

![image](https://github.com/MohamedBassem/hoarder-app/assets/10006695/c461c633-a61a-422f-8043-3fd670b2e734)

**Comment by MohamedBassem** [comment]
this usually means that the directory of the workers is different from that of the web container. Both should be pointing to the same directory.

**Comment by talentedmrripley** [comment]
> this usually means that the directory of the workers is different from that of the web container. Both should be pointing to the same directory.

Thanks for the blisteringly fast reply, that was indeed the issue.  I had changed the path for the web container and not updated the worker to the same path.  Fixed and issue is reaolved.
